修复开启屏幕分享时会导致其她用户白屏的问题
msgbyte/tailchat-meeting pull request #13
Opened 2024-07-04 06:37 UTC by TNTcraftHIM

2024-07-04 09:21 UTC, moonrailgun commented on README.md
> +git clone https://github.com/TNTcraftHIM/tailchat-meeting --depth=1
?

2024-07-04 09:34 UTC, TNTcraftHIM commented on README.md
> +git clone https://github.com/TNTcraftHIM/tailchat-meeting --depth=1
为了方便自己部署在不同服务器上测试改了一下readme，无视就行

2024-07-13 09:15 UTC, moonrailgun commented on README.md
> +git clone https://github.com/TNTcraftHIM/tailchat-meeting --depth=1
can you remove this section? i dont think its a good idea to keep clone repo from other repo if you wanna merge this pr into this repo

2024-07-13 09:15 UTC, moonrailgun requested changes

2024-07-13 09:15 UTC, moonrailgun commented on README.md
> +git clone https://github.com/TNTcraftHIM/tailchat-meeting --depth=1
thanks

2024-07-13 09:23 UTC, TNTcraftHIM commented on README.md
> +git clone https://github.com/TNTcraftHIM/tailchat-meeting --depth=1
> can you remove this section? i dont think its a good idea to keep clone repo from other repo if you wanna merge this pr into this repo

Sure, done

2024-07-13 15:57 UTC, merged